

-- delete records versus drop partition.

set autotrace off
set echo off
set verify off
set timing off

@show_redo 

clear screen

prompt .
prompt Reset the stats, ready to delete some data and measure redo.
prompt .

accept hit_enter prompt 'Hit Enter to Continue...'

set echo on

delete from t where id < 10000;

set echo off

prompt .
prompt The redo generated by deleting from a normal table...
prompt .

@show_redo

set echo on

delete from pt where id < 10000;

set echo off

prompt .
prompt The redo generated by deleting from a partitioned table...
prompt .

@show_redo 

set echo on

alter table pt drop partition pt_2 ;

set echo off

prompt .
prompt The redo generated by dropping a partition with equal nr of records...
prompt .

prompt .

@show_redo

